# URL kết nối cơ sở dữ liệu SQL Server trực tiếp qua cổng 1433, chỉ định database là 'parking_system'
# encrypt=true và trustServerCertificate=true dùng để kích hoạt mã hóa kết nối tin cậy mà không cần chứng chỉ SSL bên thứ ba
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=parking_system;encrypt=true;trustServerCertificate=true

# Tên đăng nhập tài khoản quản trị SQL Server (mặc định là sa)
spring.datasource.username=sa

# Mật khẩu của tài khoản SQL Server (ở đây là 12345)
spring.datasource.password=12345

# Class Driver của Microsoft SQL Server JDBC dùng để kết nối Java với SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Tự động cập nhật cấu trúc bảng trong cơ sở dữ liệu nếu có sự thay đổi ở lớp thực thể Java (Slot.java)
spring.jpa.hibernate.ddl-auto=update

# Hiển thị các câu lệnh SQL mà JPA thực thi dưới màn hình Console (tiện cho việc debug)
spring.jpa.show-sql=true

# Chỉ định phương ngữ (Dialect) sử dụng cho cơ sở dữ liệu SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cổng cổng mạng (Port) mà ứng dụng web server Spring Boot sẽ lắng nghe khi chạy (mặc định 8080)
server.port=8081

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB